#Editor properties file
#Fri Jan 09 16:41:19 EST 2026
editor.showWall=0
editor.showRoad=0
editor.showBuilding=0
editor.showLake=0
editor.showTrees=0
editor.showPlot=0
editor.showObject3d=0
editor.showRiver=0
